### ISSUE TITLE
Compile libgcryptEnclave Error 

### ISSUE THREAD

**Issue by B0mb2017** [heartever/primeprobe#1]
First，I have been installed SGX_SDK
Second, when i tried to Make libgcryptEnclave folders,sth wrong!
![image](https://user-images.githubusercontent.com/30366245/57348858-68409800-718a-11e9-8da9-86294797b8e0.png)
then, i enter /opt/intel/sgx_sdk/ could not find libtstdcxx.so 
where can i find libtstdcxx.so ？
please help me , tanks!

**Comment by KoraXia** [comment]
I replace the -lsgx_tstdcxx with -lsgx_tcxx in the makefile and it works. With the update of SGX, libsgx_tstdcxx is no longer recommended and should be replaced by libsgx_tcxx. According to https://github.com/lsds/TaLoS/issues/21.
